### ISSUE TITLE
Uncaught TypeError: window.netflix.cadmium.objects.videoPlayer is not a function

### ISSUE THREAD

**Issue by arnonym** [JohnCoates/NetflixPro#3]
Since a few days I get the error

```
Uncaught TypeError: window.netflix.cadmium.objects.videoPlayer is not a function
```

in javascript console.

**Comment by JohnCoates** [comment]
Thanks, looks like Netflix changed some of their code and are no longer exposing that object. Looking into it!

**Comment by shail** [comment]
Just wondering if there was any update here? Thanks!

**Comment by shail** [comment]
Another way of rewinding is pausing the video and then using the arrow keys which allows you to rewind/fast forward by 10 seconds at a time.

**Comment by sswam** [comment]
Any luck with this?  I had a quick look at the netflix javascript code, but didn't see how to get to the object yet.  (BTW, Your blog about writing the extension was interesting to read, thanks for that.)

**Comment by AlexAllocated** [comment]
I've been trying to find a way around this as well. Grabbing the HTML5 video element and trying to manually change the `currentTime` appears to break the player. `netflix.cadmium.objects` exists but no longer has a `videoPlayer` reference there. I'm wading through minified source files but may just have to give up on this soon. Hopfeully someone else will figure out a new way to seek the Netflix player with JS.

**Comment by avigoldman** [comment]
Hey @JohnCoates any plans to update this extension?

**Comment by rdp** [comment]
I put my latest thoughts on controlling netflix here: http://stackoverflow.com/questions/27927950/controlling-netflix-html5-playback-with-tampermonkey-javascript/39703888#39703888 FWIW

**Comment by JohnCoates** [comment]
Thanks @rdp.

@avrahamgoldman: I'm accepting pull requests that bring functionality back. Development is stalled because Netflix has made it nearly impossible to get access to their internal controls.

If there's a way to get access to that Netflix object that would be great. The object gets created with no global reference to it, so I'm not sure how to grab it without modifying their code, which would be a fragile solution.

**Comment by avigoldman** [comment]
I actually developed a little (very barebones and non optimized) library that controls the netflix player.
https://github.com/avrahamgoldman/netflix.js

**Comment by JohnCoates** [comment]
Looks really nice! I might have a go at updating this extension to use your library

**Comment by avigoldman** [comment]
Let me know how it goes!! Hit me up with any suggestions or questions :D
